# Generated by Django 3.1.3 on 2022-03-12 01:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0030_auto_20211226_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 19, 1, 36, 36, 12626, tzinfo=utc)),
        ),
    ]
